#!/usr/bin/env npx tsx
/**
 * Setup Changesets + GitHub Actions across all DO ecosystem repos
 *
 * This script:
 * 1. Ensures @changesets/cli is installed
 * 2. Creates .changeset/config.json
 * 3. Creates .github/workflows/release.yml with changesets/action
 * 4. Adds prepublish scripts to package.json
 *
 * Usage:
 *   npx tsx setup-changesets.ts [--dry-run]
 */

import { execSync } from 'child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const PROJECTS_ROOT = process.env.PROJECTS_ROOT || join(process.env.HOME!, 'projects')

const REPOS = [
  { path: 'types', name: '@dotdo/types' },
  { path: 'collections', name: '@dotdo/sqlite-collections' },
  { path: 'colo', name: 'colo.do' },
  { path: 'rpc.do', name: 'rpc.do', hasCore: true },
  { path: 'oauth.do', name: 'oauth.do' },
  { path: 'fsx', name: 'fsx.do', hasCore: true },
  { path: 'gitx', name: 'gitx-monorepo', isMonorepo: true },
  { path: 'bashx', name: 'bashx.do', hasCore: true },
  { path: 'do', name: '@dotdo/do' },
  { path: 'cli.do', name: '@dotdo/cli' },
]

const CHANGESET_CONFIG = {
  $schema: 'https://unpkg.com/@changesets/config@3.0.0/schema.json',
  changelog: '@changesets/cli/changelog',
  commit: false,
  fixed: [],
  linked: [],
  access: 'public',
  baseBranch: 'main',
  updateInternalDependencies: 'patch',
  ignore: [] as string[],
}

// OIDC Trusted Publishing workflow - no NPM_TOKEN needed!
// Requires: npm trusted publisher configured for each package on npmjs.com
// See: https://docs.npmjs.com/trusted-publishers
const RELEASE_WORKFLOW = `name: Release

on:
  push:
    branches:
      - main

concurrency: \${{ github.workflow }}-\${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write  # Required for OIDC trusted publishing

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24  # Node 24+ includes npm with OIDC support
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test || true

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version
          title: 'chore: version packages'
          commit: 'chore: version packages'
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          # No NPM_TOKEN needed - uses OIDC trusted publishing!
`

const CHANGESET_README = `# Changesets

Hello and welcome! This folder has been automatically generated by \`@changesets/cli\`.

## How to add a changeset

1. Run \`pnpm changeset\` in the root of the repo
2. Select the packages you want to include in the changeset
3. Select the type of change (major, minor, patch)
4. Write a summary of the changes

## How to release

1. Push your changes to main (or merge a PR)
2. The GitHub Action will create a "Version Packages" PR
3. Review and merge the PR to publish to npm

For more info, see [changesets documentation](https://github.com/changesets/changesets).
`

function log(msg: string) {
  console.log(msg)
}

function logSuccess(msg: string) {
  console.log(`\x1b[32m✓ ${msg}\x1b[0m`)
}

function logWarning(msg: string) {
  console.log(`\x1b[33m⚠ ${msg}\x1b[0m`)
}

function logError(msg: string) {
  console.log(`\x1b[31m✗ ${msg}\x1b[0m`)
}

function setupRepo(repoConfig: (typeof REPOS)[0], dryRun: boolean) {
  const repoPath = join(PROJECTS_ROOT, repoConfig.path)

  log(`\n${'='.repeat(50)}`)
  log(`Setting up: ${repoConfig.name}`)
  log(`Path: ${repoPath}`)
  log('='.repeat(50))

  if (!existsSync(repoPath)) {
    logWarning(`Repository not found: ${repoPath}`)
    return
  }

  // 1. Setup .changeset directory
  const changesetDir = join(repoPath, '.changeset')
  if (!existsSync(changesetDir)) {
    if (dryRun) {
      log(`[DRY RUN] Would create: ${changesetDir}`)
    } else {
      mkdirSync(changesetDir, { recursive: true })
      logSuccess(`Created .changeset directory`)
    }
  }

  // 2. Create/update config.json
  const configPath = join(changesetDir, 'config.json')
  const config = { ...CHANGESET_CONFIG }

  // For monorepos, ignore the root package
  if (repoConfig.isMonorepo) {
    config.ignore = [repoConfig.name]
  }

  if (dryRun) {
    log(`[DRY RUN] Would write: ${configPath}`)
  } else {
    writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n')
    logSuccess(`Created .changeset/config.json`)
  }

  // 3. Create README
  const readmePath = join(changesetDir, 'README.md')
  if (dryRun) {
    log(`[DRY RUN] Would write: ${readmePath}`)
  } else {
    writeFileSync(readmePath, CHANGESET_README)
    logSuccess(`Created .changeset/README.md`)
  }

  // 4. Setup GitHub workflows directory
  const workflowsDir = join(repoPath, '.github', 'workflows')
  if (!existsSync(workflowsDir)) {
    if (dryRun) {
      log(`[DRY RUN] Would create: ${workflowsDir}`)
    } else {
      mkdirSync(workflowsDir, { recursive: true })
      logSuccess(`Created .github/workflows directory`)
    }
  }

  // 5. Create/update release.yml
  const releasePath = join(workflowsDir, 'release.yml')
  if (dryRun) {
    log(`[DRY RUN] Would write: ${releasePath}`)
  } else {
    writeFileSync(releasePath, RELEASE_WORKFLOW)
    logSuccess(`Created .github/workflows/release.yml`)
  }

  // 6. Update package.json with scripts
  const packageJsonPath = join(repoPath, 'package.json')
  if (existsSync(packageJsonPath)) {
    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'))

    // Add/update scripts
    packageJson.scripts = packageJson.scripts || {}

    // Prepublish should run build and test
    if (!packageJson.scripts.prepublishOnly) {
      packageJson.scripts.prepublishOnly = 'pnpm build'
    }

    // Version script for changesets
    if (!packageJson.scripts.version) {
      packageJson.scripts.version = 'changeset version'
    }

    // Release script - uses --provenance for OIDC trusted publishing
    if (!packageJson.scripts.release) {
      packageJson.scripts.release = 'pnpm build && changeset publish --provenance --access public'
    }

    if (dryRun) {
      log(`[DRY RUN] Would update package.json scripts`)
    } else {
      writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n')
      logSuccess(`Updated package.json scripts`)
    }
  }

  // 7. Install @changesets/cli if not present
  if (!dryRun) {
    try {
      const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'))
      const hasChangesets = packageJson.devDependencies?.['@changesets/cli'] || packageJson.dependencies?.['@changesets/cli']

      if (!hasChangesets) {
        log(`  Installing @changesets/cli...`)
        execSync('pnpm add -D @changesets/cli', { cwd: repoPath, stdio: 'pipe' })
        logSuccess(`Installed @changesets/cli`)
      } else {
        logSuccess(`@changesets/cli already installed`)
      }
    } catch (err) {
      logWarning(`Could not install @changesets/cli: ${err}`)
    }
  }
}

function main() {
  const dryRun = process.argv.includes('--dry-run')

  log('\n🔧 DO Ecosystem Changesets Setup\n')

  if (dryRun) {
    logWarning('DRY RUN MODE - No files will be modified\n')
  }

  for (const repo of REPOS) {
    setupRepo(repo, dryRun)
  }

  log('\n' + '='.repeat(50))
  log('Setup Complete!')
  log('='.repeat(50))

  log(`
Next steps:

1. Configure OIDC Trusted Publisher for each npm package:
   - Go to npmjs.com/package/<package-name>/access
   - Click "Add trusted publisher"
   - Select "GitHub Actions"
   - Enter:
     • Owner: <your-github-org>
     • Repository: <repo-name>
     • Workflow: release.yml
     • Environment: (leave blank)
   - Save

   Note: Package must exist on npm first. For new packages,
   publish once manually with: npm publish --provenance --access public

2. Create a changeset:
   cd ~/projects/<repo>
   pnpm changeset

3. Push to main:
   git add .
   git commit -m "chore: add changeset"
   git push

4. GitHub Action creates "Version Packages" PR automatically

5. Merge the PR → Published to npm via OIDC (no tokens needed!)

Benefits of OIDC Trusted Publishing:
- No long-lived tokens to manage or rotate
- Automatic provenance attestation
- More secure supply chain
- See: https://docs.npmjs.com/trusted-publishers
`)
}

main()
